Remove install_role

diff --git a/oneops-ansible-role-init b/oneops-ansible-role-init
--- a/oneops-ansible-role-init
+++ b/oneops-ansible-role-init
@@ -10,26 +10,22 @@ set -u # abort on unbound variable
 usage() {
 cat << _EOF_
 Usage: ${0} PROJECT_NAME [ROLE]...
-  Initialises a Vagrant+Ansible project based on
+  Initialises a new Ansible role project based on
   https://github.com/bertvv/ansible-skeleton
-  and optionally, installs the specified roles from Ansible Galaxy
 _EOF_
 }
 
-install_role() {
-  # First, try to install from Ansible Galaxy directly
-  ansible-galaxy install -p ansible/roles "${1}"
-
-  if [ "$?" -ne "0" ]; then
-    echo " ## This does not seem to be an Ansible role. Trying Github"
-    user=${1%%\.*}
-    role=${1##*\.}
-    rolename=${role##ansible-}
-    git_url="https://github.com/${user}/${role}.git"
-    echo " ## => ${git_url}"
-    git clone "${git_url}" "ansible/roles/${user}.${rolename}"
-  fi
-}
+while getopts ":a" opt; do
+  case $opt in
+    a)
+      echo "-a was triggered!" >&2
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
 
 if [ "$#" -lt "1" ]; then
     echo "Expected at least 1 argument, got $#" >&2
@@ -60,7 +56,3 @@ git init "${project}"
 cd "${project}" || exit
 git add .
 git commit --message "Initial commit"
-
-for role in "${@}"; do
-  install_role "${role}"
-done
